pool:  
  name: Azure Pipelines
  demands: npm
trigger:
  branches:
    include:
    - main

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    languages: javascript,csharp
- task: Npm@1
  displayName: 'npm ci'  
  inputs:    
    workingDir: ArkWebApp
    verbose: true
- task: Npm@1
  displayName: 'npm list'  
  inputs:    
    workingDir: ArkWebApp
    verbose: true
- task: Npm@1
  displayName: 'Angular APP Run build'  
  inputs:    
    command: custom
    workingDir: ArkWebApp
    verbose: false    
    customCommand: 'set NODE_OPTIONS=--openssl-legacy-provider'
- task: Npm@1
  displayName: 'Angular APP Run build'  
  inputs:    
    command: custom
    workingDir: ArkWebApp
    verbose: true    
    customCommand: 'run ng build -- --configuration=production'
- task: ArchiveFiles@2
  displayName: 'Archive files'  
  inputs:    
    rootFolderOrFile: 'ArkWebApp/dist/ArkWebApp'    
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'